{% set name = "qdatamatrix" %}
{% set pypiname = "python-" + name %}
{% set version = "0.1.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: 9724e52e75c53f65a49afa056c3a11222d8d7f42a85c20572d4df39407cf977d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - qtpy
    - pyqt
    - datamatrix

  run:
    - python
    - qtpy
    - pyqt
    - datamatrix

test:
  imports:
    - qdatamatrix

about:
  home: https://github.com/smathot/python-qdatamatrix
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: A PyQt4/PyQt5 widget for viewing and editing a DataMatrix object.
  dev_url: https://github.com/smathot/python-qdatamatrix

extra:
  recipe-maintainers:
    - dschreij
    - smathot
