{% set name = "qdatamatrix" %}
{% set pypiname = "python-" + name %}
{% set version = "0.1.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz"
  sha256: "efa00b89da6f313ed0d406f48391ff3f520ff6198f87ad271597d22c2cc604fa"

build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]

  host:
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - xorg-libxfixes  # [linux]
    - pip
    - python
    - qtpy
    - pyqt
    - datamatrix

  run:
    - python
    - qtpy
    - pyqt
    - datamatrix

test:
  imports:
    - qdatamatrix

about:
  home: https://github.com/smathot/python-qdatamatrix
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: 'A PyQt4/PyQt5 widget for viewing and editing a DataMatrix object.'
  dev_url: https://github.com/smathot/python-qdatamatrix

extra:
  recipe-maintainers:
    - dschreij
    - smathot
