{% set name = "qdatamatrix" %}
{% set pypiname = "python-" + name %}
{% set version = "0.1.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: 547c370944967db4e046d1fcd8f3e6a4bf4db54b7548ae10c432195c513170da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - qtpy
    - pyqt
    - datamatrix

  run:
    - python >=3.6
    - qtpy
    - pyqt
    - datamatrix

test:
  imports:
    - qdatamatrix

about:
  home: https://github.com/smathot/python-qdatamatrix
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A PyQt4/PyQt5 widget for viewing and editing a DataMatrix object.
  dev_url: https://github.com/smathot/python-qdatamatrix

extra:
  recipe-maintainers:
    - dschreij
    - smathot
